spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/OOAD_v1
    username: root
    password: *
  servlet:
    multipart:
      enabled: true
      max-file-size: 1000MB
      max-request-size: 1000MB

mybatis:
  configuration:
    # map even if select null
    call-setters-on-nulls: true
    map-underscore-to-camel-case: false
    auto-mapping-behavior: full

server:
  port: 8075


aliyun:
  vod:
    file:
      keyid: LTAI5tNg1V1AeGdZkZFdcbrH
      keysecret: t1oPigpg6B77RXcxNrdPnxnGBwIDk7
  oss:
    file:
      endpoint: oss-cn-shenzhen.aliyuncs.com
      keyid: LTAI5tNg1V1AeGdZkZFdcbrH
      keysecret: t1oPigpg6B77RXcxNrdPnxnGBwIDk7
      bucketname: ooadproject1




